### ISSUE TITLE
Does falcor.net support {keys} Pattern?

### ISSUE THREAD

**Issue by mbukosky** [falcordotnet/falcor.net#10]
Hi,

I have been playing around with the sample code and was wondering if the current code supports {keys} pattern?

[Falcor-Router](http://netflix.github.io/falcor/documentation/router.html)

>The {keys} Pattern

>The {keys} pattern will match any valid key (string, number, boolean), or KeySet (an array of ranges or keys) and normalize the matching set of keys into an Array of keys.

>For example…

`genreList[0, 2..4, "length"]`
>…matched against…

`genreList[{keys}]`
>…will produce the following Path Sets to be passed to the route handler:

`["genreList", [0, 2, 3, 4, "length"]]`

I was thinking that if it was supported, this route would work. But I can't get it working because I keep getting a parsing error from the client request. Any ideas?

```csharp
Get["titlesById[{keys:ids}][{keys:props}]"] = async parameters => {
	var ids = parameters.ids;

	//...

	return Complete(results);
};
```

**Comment by craigsmitham** [comment]
Falcor.NET does support the {keys} pattern, but it only supports matching against keys that are `SimpleKey`s: numbers, strings, or nulls. This is not very clear from the tests currently, and I've added an issue #12 that should address some of the confusion. 

The Falcor documentation is also not very clear about this, but this implementation is based on the Java version (http://mvnrepository.com/artifact/com.netflix.falcor). This same thing stumped me for awhile, but I realized there is not really a good rationale for why you would support the more complex keys (ranges, integer sets, etc.) inside the "keys" pattern.

**Comment by mbukosky** [comment]
I see the SimpleKey code but I am not sure how to call it from the client. 

I would expect to call it via `[["genrelist",["51f2928f34","a32e8912f34"],"name"]]`. Is there a different way to call it from the client?

>This same thing stumped me for awhile, but I realized there is not really a good rationale for why you would support the more complex keys (ranges, integer sets, etc.) inside the "keys" pattern.

I am not sure about this, how would the routing support indexing with Guids? This is a valid use case for the keys pattern. Netflix even talks about it in there blog post

[This pattern is most often when matching entities by a GUID. For example, the following route builds a map of all titles by GUID.](http://netflix.github.io/falcor/documentation/router.html)

**Comment by mbukosky** [comment]
From looking at the PathGrammer.cs, it looks like the mix case of digits and letters is killing the parser. I am digging into the code, but not really sure where to look.

These fail
`[["genrelist",["51f2928f34","a32e8912f34"],"name"]]`
`[["genrelist",["1","1"],"name"]]`

Pass
`[["genrelist",["foo","bar"],"name"]]`

**Comment by craigsmitham** [comment]
This is probably what you're looking for: https://github.com/falcordotnet/falcor.net/blob/09cc72675f22fed5f1682a4c715dc46509ded0e5/src/Falcor.Server/Routing/PathParser/PathGrammar.cs#L54

It should probably be `LetterOrDigit` instead. Technically ... according to the JSON spec, it could also include whitespace.

**Comment by craigsmitham** [comment]
Probably should really be anything that is double quoted ... I'm thinking of GUIDs that could contain dashes as well. I was focusing on the most narrow happy path use case to get the parser working, but it could probably be generalized/fixed now that we have some good tests around it.

**Comment by mbukosky** [comment]
Bingo!

That fixed the unit tests. Do you want me to put together a PR for the fix?

FYI, this now passes with the fix above

```csharp
[Scenario]
[Example(@"""foo""", "foo")]
[Example(@"""bar""", "bar")]
[Example(@"""baz""", "baz")]
[Example("\"51f2928f34\"", "51f2928f34")]
public void StringKey(string input, string expected) => 
	Assert.Equal(new StringKey(expected), PathGrammar.StringKey.Parse(input));	
``

**Comment by craigsmitham** [comment]
Sure - would you mind making using spaces for the whitespace? I'll put some coding conventions in here soon, but for now just follow general existing style you see. Suggestions welcome.

**Comment by mbukosky** [comment]
Sure, I will try to put something together. I'll also put in a case for Guid and spaces.

**Comment by mbukosky** [comment]
I have a possible fix for this with my [commits](https://github.com/mbukosky/falcor.net/commit/1de371ace4d8447406e333d15ab37174aa432c54)

I wanted to add a working example in the example projects before I send off the PR. Will try and do that tomorrow.

**Comment by mbukosky** [comment]
PR #13 

Let me know what you think
