### ISSUE TITLE
SerializeItem doesn't support boolean

### ISSUE THREAD

**Issue by darcy-buttrose** [falcordotnet/falcor.net#18]
There is no allowance in ResponseSerializer.SerializeItem or SerializationHelper.SerializeItem for a value of type bool. The fix I discovered is to insert a new line in both that looks like:

            if (value is bool) return new JValue((bool)value);

Should I create a PR with code changes and test or will someone else do that.

**Comment by craigsmitham** [comment]
Fixed with #19
